### ISSUE TITLE
[?] Seeking a recommendation: QuikGraph integration

### ISSUE THREAD

**Issue by HG-Dev** [Cysharp/ObservableCollections#40]
I'm interested in integrating ObservableCollection interfaces with QuikGraph to support the use of a directed graph as a model with MVVM architecture, but the complexity of creating an `ISynchronizedView` or `ISortableSynchronizedView` for graphs has left me puzzled. In QuikGraph, there are multiple types of collections used to store **vertex** and **edge** information, but the most common structure can be summed up as:

1. A list of `<TVertex>`
2. A dictionary mapping `<TVertex>` to `List<TEdge> where TEdge : IEdge<TVertex>`. IEdge guarantees that TEdge has TVertex Source and TVertex Target properties.

QuikGraph provides an interface with events for vertex addition / removal and edge addition / removal. We can interpret this to mean that one graph has two "observable" views: the vertex list, and all edges regardless of vertex. We could also view the graph to be a `Dictionary<TVertex, List<TEdge>>`, but this would imply an `ObservableDictionary<TVertex, ObservableList<TEdge>>`... and this brings us back to the integration problem.

Putting aside the QuikGraph dependency for a moment, what would be a valid synchronized view for a graph? Some ideas...
- Implement IObservableCollection for both `<TVertex>` and `<TEdge>`, and require CreateView to be used via IObservableCollection<>.CreateView
- Layer IObservableCollection such that one view allows for the creation of another view, i.e. `IObservableCollection<KeyValuePair<TVertex, IObservableCollection<TEdge>>>`. (big code smell here)
- Instead of implementing interfaces directly on the Graph class, have public IObservableCollection properties for vertices and edges
- Create an entirely new IObservableDataTable interface and do not treat inter-collection "relations" as additional collection objects <- This might be the conceptually soundest solution.

I'd be thrilled if I could get some advice on observing these sorts of complex collections.

**Comment by TaviTruman** [comment]
Hi HG-Dev,

Integrating ObservableCollections from Cysharp with QuikGraph for an MVVM architecture can indeed be challenging. Here's a structured approach to help you achieve this, focusing on creating a synchronized view for your graph.

Integrating ObservableCollection Interfaces with QuikGraph
Overview
We'll use ObservableDictionary and ObservableList from ObservableCollections to manage vertices and edges. This will ensure thread-safety and high performance, and allow us to create synchronized views for MVVM.

Implementation
Step 1: Define ObservableGraph
First, we define an ObservableGraph class to manage our vertices and edges:

`using ObservableCollections;

public class ObservableGraph<TVertex, TEdge> where TEdge : IEdge<TVertex>
{
    public ObservableDictionary<TVertex, ObservableList<TEdge>> AdjacencyList { get; } = new ObservableDictionary<TVertex, ObservableList<TEdge>>();

    public ObservableGraph()
    {
        // Subscribe to events if necessary
    }

    public void AddVertex(TVertex vertex)
    {
        if (!AdjacencyList.ContainsKey(vertex))
        {
            AdjacencyList[vertex] = new ObservableList<TEdge>();
        }
    }

    public void RemoveVertex(TVertex vertex)
    {
        if (AdjacencyList.ContainsKey(vertex))
        {
            AdjacencyList.Remove(vertex);
        }
    }

    public void AddEdge(TEdge edge)
    {
        if (!AdjacencyList.ContainsKey(edge.Source))
        {
            AddVertex(edge.Source);
        }

        if (!AdjacencyList.ContainsKey(edge.Target))
        {
            AddVertex(edge.Target);
        }

        AdjacencyList[edge.Source].Add(edge);
    }

    public void RemoveEdge(TEdge edge)
    {
        if (AdjacencyList.ContainsKey(edge.Source))
        {
            AdjacencyList[edge.Source].Remove(edge);
        }
    }
}
`

Step 2: Create ViewModel for MVVM
Next, we create a ViewModel to expose the graph data to the view:

`using ObservableCollections;
using System.Linq;

public class GraphViewModel<TVertex, TEdge> where TEdge : IEdge<TVertex>
{
    public ObservableGraph<TVertex, TEdge> Graph { get; }

    public INotifyCollectionChangedSynchronizedView<KeyValuePair<TVertex, ObservableList<TEdge>>> VerticesView { get; }
    public INotifyCollectionChangedSynchronizedView<TEdge> EdgesView { get; }

    public GraphViewModel()
    {
        Graph = new ObservableGraph<TVertex, TEdge>();

        // Create views for vertices and edges
        VerticesView = Graph.AdjacencyList.CreateView(kvp => kvp).ToNotifyCollectionChanged();
        EdgesView = Graph.AdjacencyList.SelectMany(kvp => kvp.Value).CreateView(edge => edge).ToNotifyCollectionChanged();
    }

    // Additional methods and properties to facilitate binding and command handling in MVVM
}
`

Step 3: Integrate with WPF
Finally, we bind the ViewModel to our WPF UI:

MainWindow.xaml:

`<Window x:Class="YourNamespace.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        Title="Observable Graph" Height="350" Width="525">
    <Grid>
        <ListBox ItemsSource="{Binding VerticesView}" DisplayMemberPath="Key" />
        <ListBox ItemsSource="{Binding EdgesView}" DisplayMemberPath="Source" />
    </Grid>
</Window>
`

MainWindow.xaml.cs:

`using System.Windows;

namespace YourNamespace
{
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
            DataContext = new GraphViewModel<int, Edge<int>>(); // Assuming Edge<TVertex> implements IEdge<TVertex>
        }
    }
}
`

This approach leverages ObservableCollections for efficient and thread-safe data handling in a graph structure, fitting neatly within the MVVM pattern. The synchronized views ensure that changes in the graph model are automatically reflected in the UI, making the application responsive and maintainable.

Key Points:

ObservableGraph: Manages the graph structure using ObservableDictionary and ObservableList.
GraphViewModel: Creates synchronized views for vertices and edges, suitable for data binding.
WPF Integration: Binds the ViewModel to the UI, ensuring updates in the model reflect in the view.

**Comment by HG-Dev** [comment]
Err, thanks ChatGPT.

**Comment by TaviTruman** [comment]
@HG-Dev Okay let me fix this and the code I posted does not work!

**Comment by TaviTruman** [comment]
> Err, thanks ChatGPT.

Okay, I have updated my experiment based on your requirements using QuickGraph, R3 and ObservableCollection; I am also attaching the VS project for your review. Was a fun bit of coding :-)

[QuickGraphDemo.zip](https://github.com/user-attachments/files/15749913/QuickGraphDemo.zip)
