### ISSUE TITLE
Requests when used in combination with R3

### ISSUE THREAD

**Issue by TORISOUP** [Cysharp/ObservableCollections#44]
I have two requests.

### 1. readonly-observable-Dictionary

The `IReadonlyReactiveDictionary` that existed in UniRx was easy to use, so we request a function equivalent to it.
If I tried to handle the current `ObservableDictionary` Readonly, I would have to divide it into two parts, `IReadonlyDictionary` and `IObservableCollection<KeyValuePair>`, which is not easy to handle.

### 2.   Publish OnCompleteMessage from IObservableCollection.

When dealing with IObservableCollection in R3, I feel uncomfortable that it is not possible to unsubscribe from the collection side.
For example, could it be possible to make IObservableCollection inherit IDisposable and issue OnCompleted on Dispose()?

**Comment by neuecc** [comment]
When the CancellationToken of each subscription method (ObserveAdd, etc...) of R3Extensions is canceled, OnCompleted will be issued.
This is the same behavior as R3's Observable.Timer, etc.
