### ISSUE TITLE
Getting old and new index in ChangeKind.Moved 

### ISSUE THREAD

**Issue by slimshader** [Cysharp/ObservableCollections#5]
Hi, components like Vertical/HorizontalLayoutGroup arrange their elements based on relative order of children inside parent GameObjects. This means game objects has to be moved too when it moves in underlying ObservableList. I am not sure tho how to do it when ChangeKind.Moved happened as there are no index parameters.

[Edit] Very sorry for all the edits. lost connection and things got messed up.

**Comment by neuecc** [comment]
Thank you for trying it.
I added `in NotifyCollectionChangedEventArgs<T> eventArgs` as an argument in 1.1.0.
However, this is a very primitive value, and also potentially difficult to handle correctly when batching (Move doesn't have batche, so it's okay).

**Comment by slimshader** [comment]
Fantastic, thank you, will try it out asap. And thank you for another fantastic library.
