### ISSUE TITLE
ObservableList<T>.View implements IReadOnlyCollection but not IReadOnlyList

### ISSUE THREAD

**Issue by jphorv-bdo** [Cysharp/ObservableCollections#53]
It would be very useful if `ObservableList<T>.View` implemented `IReadOnlyList` so that an indexer can be used.
A workaround is to use the ElementAt LINQ extension method, but that very expensive compared to a direct indexed lookup.

**Comment by neuecc** [comment]
The filter mechanism is incompatible with the indexer.
However, I would like to think of some drastic countermeasures.

In v1.2.0, I implemented `IList<TView>` in the NotifyCollectionChanged View.
So, as a workaround, it is possible to cast it to `IReadOnlyList<T>` after `ToNotifyCollectionChanged`.

**Comment by jphorv-bdo** [comment]
Ah yes. Thank you for thinking about a workaround.

Just some thoughts/idea here...

What about a new property on the view, something like (pseudo-code):

```
class View<TView>
{
    IReadOnlyList<T> Unfiltered { get; } = new ReadOnlyListView<T>(this.list);
}
```

where `ReadOnlyListView<T>` is some wrapper enforcing read-only. Or if that's overkill, the same property but it returns the inner list directly. Or if a property isn't the right fit, a method like `AsUnfiltered()`?

**Comment by neuecc** [comment]
Thank you for advice, v3 added `Filtered` and `Unfiltered` for view(but it is IEnumerable)
Andalso defined `ToViewList()`.
