### ISSUE TITLE
In WPF, Item selection changes isn't reflected in View

### ISSUE THREAD

**Issue by hsytkm** [Cysharp/ObservableCollections#58]
## Issue
When creating `ISynchronizedView<T, TView>` using `ObservableList<T>.CreateView()`, if type conversion is performed in the `transform`, changes to the selected item in View isn't reflected.

## Demo
![demo](https://github.com/user-attachments/assets/843263d5-ee3f-47c1-9a0c-1cc816cf7fb1)

## Environment
- Visual Studio 2022 17.11.0
- .NET8
- WPF
- ObservableCollections Version="2.2.0"

## Repository
[OCSelectedItemWpfDemo - GitHub](https://github.com/hsytkm/OCSelectedItemWpfDemo)

**Comment by zerodev1200** [comment]
https://github.com/runceel/ReactiveProperty/issues/487#issuecomment-2291369293_

I’m not sure if the cause is the same, but I have confirmed that reverting to v2.1.4 or removing the non-generic IList also resolves this issue, just like the one mentioned above.
