### ISSUE TITLE
Add Constructor Overload for Initial Capacity in ObservableDictionary<TKey, TValue>

### ISSUE THREAD

**Issue by toculin38** [Cysharp/ObservableCollections#59]
It would be beneficial to add a constructor overload to ObservableDictionary<TKey, TValue> that accepts an initial capacity. This would allow users to preallocate the internal dictionary's capacity when the approximate number of elements is known in advance, leading to potential performance improvements by reducing the need for internal resizing.

`
public ObservableDictionary(int capacity) 
{
    this.dictionary = new Dictionary<TKey, TValue>(capacity);
}
`

This constructor overload would mirror the existing Dictionary<TKey, TValue> constructor that takes an initial capacity.

Use Case:
When working with large collections or in performance-critical applications, being able to set the initial capacity of a collection can reduce memory allocations and improve efficiency by avoiding unnecessary resizing. Adding this constructor would make ObservableDictionary<TKey, TValue> more versatile and performant in such scenarios.

**Comment by neuecc** [comment]
v2.2.1 support it.
