### ISSUE TITLE
Best way to add to Unity project?

### ISSUE THREAD

**Issue by keenanwoodall** [Cysharp/ObservableCollections#6]
In the Getting Started section of the README it says to read the [Unity](https://github.com/Cysharp/ObservableCollections#unity) section, but the section does not mention how to install. I do not believe it's possible to install it through nuget in the package manager, and there isn't a upm branch.

Are we meant to clone the repo and extract the Unity code into a project as a local package, or is there a way to add the package via Package Manager?

Apologies if this is a silly question! Thanks for making something a slick package - I just want to make sure I'm using it correctly :)

**Comment by neuecc** [comment]
UPM git URL package or asset package(ObservableCollections.*.unitypackage) in releases page.

git URL is
`https://github.com/Cysharp/ObservableCollections.git?path=src/ObservableCollections.Unity/Assets/Plugins/ObservableCollections`

I'll write this info to ReadMe, thanks.

**Comment by keenanwoodall** [comment]
Thank you! Would it be possible to move the additional System dlls into that folder so they are included with the package? As is, it won't compile after install through upm unless the dlls are copied manually into the Assets/

**Comment by neuecc** [comment]
We do not bundle dlls with package manager.
If you do, it will cause conflicts when you add other packages.
Also, the latest version of Unity (netstandard2.1) does not require it, so this also conflicts.
