### ISSUE TITLE
When using ObservableDictionary.ToNotifyCollectionChanged in WinUI 3, the application crashes

### ISSUE THREAD

**Issue by dalian-spacekey** [Cysharp/ObservableCollections#71]
* Convert ObservableDictionary to INotifyCollectionChangedSynchronizedViewList
* Bind it to ListView for display
* After adding an item to the dictionary, the application exits without throwing any exceptions

From SynchronizedViewList.cs line 852
↓
To NotifyCollectionChangedEventHandler.cs line 62, where the application exits.

Sample project: https://github.com/dalian-spacekey/ObservableCollections/tree/winui3_dictionary

**Comment by neuecc** [comment]
Thank you.
For Dictionary, I have to modify the StartingIndex of the notification event.
I had corrected it for Filtered and the other events, but somehow only omitted Add for Nonfiltered!
I have released a fix in 3.0.4.
