### ISSUE TITLE
Request R3 with ISynchronizedView

### ISSUE THREAD

**Issue by kyubuns** [Cysharp/ObservableCollections#78]
I want to create a view in Unity as follows.

```csharp
var view = observableList.CreateView(x => new GameObject(x));
view
    .ObserveViewChanged() // <- I want this
    .SubscribeAwait(async (x, ct) =>
    {
        if (x.Action == NotifyCollectionChangedAction.Add)
        {
            await AddAnimation(args.NewItem.View, ct);
        }
        if (x.Action == NotifyCollectionChangedAction.Remove)
        {
            await RemoveAnimation(args.OldItem.View, ct);
            Destroy(args.OldItem.View);
        }
    })
    .AddTo(this);
```

However, I didn't know the best way to pass the ref struct SynchronizedViewChangedEventArgs to a Task (or to an Observable), so I would be happy if there was an official implementation.

**Comment by neuecc** [comment]
Thank you for the request, in `v3.2.0` added `ObserveChanged()`.

**Comment by kyubuns** [comment]
@neuecc 
Thanks for the implementation!
Oops, this PR was another request to Subscribe in R3 to ISynchronizedView...!

**Comment by neuecc** [comment]
Oh, sorry!
I’ll check it.

**Comment by neuecc** [comment]
v3.3.0 added subscribe view event feature.
