### ISSUE TITLE
Would you consider removing sealed class please?

### ISSUE THREAD

**Issue by pboisso** [Cysharp/ObservableCollections#79]
Hi,

Experimentation is doing well and I would like to inherit from ObservableCollections to add up some extras that would not be useful for the community.  However sealed class is preventing it. Would you consider removing this restriction?

Thanks for the consideration.

P

**Comment by neuecc** [comment]
Can't you use an extension method?
I'm concerned that inheritance won't allow you to use appropriate locks or observe.
It would be easier to understand if you could give me just one concrete example.

**Comment by pboisso** [comment]
I would like to add an UpdateRange method based on a key from the object type for example. Maybe this could be done in the library after all, with a comparer?  Would prefer that than an extension where I do multiple single update.

**Comment by pboisso** [comment]
Same for ReplaceRange support, which currently is done in 2 notifications, clear + addrange. I wish I could add a ReplaceRange option where only one notification would be sent at the end.

**Comment by neuecc** [comment]
ok, v3.2.0 removes sealed.

**Comment by pboisso** [comment]
Amazing, thank you and will definitely be careful about replicating the same locks and observe pattern. Thanks!
