### ISSUE TITLE
Request for virtual public methods

### ISSUE THREAD

**Issue by anavgar** [Cysharp/ObservableCollections#81]
Now that we can inherit from ObservableList, it would be useful if we could override the public methods such as Add or Remove, which requires those base methods to be marked as virtual.

**Comment by neuecc** [comment]
These are not designed to be inherited, so I think there is more risk.
What kind of use cases are there?

**Comment by anavgar** [comment]
I use a Memento pattern, and I need to register every addition and removal on my collections. My implementation would be something like this pseudocode:
![image](https://github.com/user-attachments/assets/1700dcb0-6255-4db8-8f3c-359ac839493f)

**Comment by neuecc** [comment]
Hmm, I hope they can resolve this through delegation.
