### ISSUE TITLE
Running filter for initial elements

### ISSUE THREAD

**Issue by slimshader** [Cysharp/ObservableCollections#9]
Hi,

because filter is attached to the view after creation it is not run for the elements that already in the collection when the view is being created. This breaks Unity example that sets parent in the filer Add event.

What is the correct solution?
1. Add the same logic as in the filter Add in the CreateView() factory? (setting parent on creation)
2. Is there a way to run filter on creation?

**Comment by Kevdome3000** [comment]
bump

**Comment by slimshader** [comment]
> I have exactly the smae problem @slimshader have you found any solution?

had too many issues with this one, went with different solution
